PATCH http://localhost:5000/reviews/like/57d48ea4-4b60-48c1-bcfd-09fc7daea655
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxZUlkIjoiYjBjMWFjYWMtOGUwYS00Y2NhLWI4ZjAtYzQyZjdhMDc1Yzc5IiwidXNlck5hbWUiOiJjb21tZW50VGVzdCIsInJldmlld2VyIjpmYWxzZSwiYWRtaW5MZXZlbCI6MCwiaXNCYW5uZWQiOmZhbHNlLCJpYXQiOjE2NTE4MTk3NDJ9.E7R_bZ1nJ4eFbczdEanm7kiMqZJOKOVx-iNeR5OOmhA

###

POST http://localhost:5000/reviews/comment/57d48ea4-4b60-48c1-bcfd-09fc7daea655
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxZUlkIjoiYjBjMWFjYWMtOGUwYS00Y2NhLWI4ZjAtYzQyZjdhMDc1Yzc5IiwidXNlck5hbWUiOiJjb21tZW50VGVzdCIsInJldmlld2VyIjpmYWxzZSwiYWRtaW5MZXZlbCI6MCwiaXNCYW5uZWQiOmZhbHNlLCJpYXQiOjE2NTE4MTk3NDJ9.E7R_bZ1nJ4eFbczdEanm7kiMqZJOKOVx-iNeR5OOmhA

{
    "commentBody": "I love that one, so tasty!"
}