POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "userName": "commentTest",
    "email": "comment@gmail.com",
    "password": "123456"
}

###

POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "comment@gmail.com",
    "password": "123456"
}

### 

GET http://localhost:5000/users/me
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxZUlkIjoiOGQ5MzA5MjMtNWFjMS00ZjYwLWJmZTctOTMzNjIxMmE0ZGU5IiwidXNlck5hbWUiOiJSYXZpZFJhdmlkIiwicmV2aWV3ZXIiOmZhbHNlLCJhZG1pbkxldmVsIjoyLCJpc0Jhbm5lZCI6dHJ1ZSwiaWF0IjoxNjUxODE5NjI5fQ.k0TghmDn6knpKiQQWaK039RKZUDO5p5oZ2su6yRa3-U

###

PUT http://localhost:5000/users/me/update
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxZUlkIjoiN2JjYjc0NGItNGUwMi00OGJkLWEwZjktMjAxNTk3ZTVlMGUzIiwidXNlck5hbWUiOiJBbG1lZ0FsbWVnIiwicmV2aWV3ZXIiOnRydWUsImFkbWluTGV2ZWwiOjMsImlhdCI6MTY1MTYwMTkwOH0.T5pIcdR4qecFs5jOu8wd9pw0-gVUS22ah8Hj0FNsbd0

{
    "userName": "AlmegAlmeg",
    "email": "almogattal@gmail.com",
    "password": "123456",
    "newPassword": "AlmegAlmeg318"
}

###

